<a href="https://colab.research.google.com/github/prashanthvijayaraja-tmu/CIND-820/blob/main/CIND820_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

In [4]:
nullfree_crashes_df = pd.read_csv('model_df.csv')

In [5]:
label_encoder = preprocessing.LabelEncoder()
nullfree_crashes_df['device_condition']= label_encoder.fit_transform(nullfree_crashes_df['device_condition'])
nullfree_crashes_df['weather_condition']= label_encoder.fit_transform(nullfree_crashes_df['weather_condition'])
nullfree_crashes_df['lighting_condition']= label_encoder.fit_transform(nullfree_crashes_df['lighting_condition'])
nullfree_crashes_df['first_crash_type']= label_encoder.fit_transform(nullfree_crashes_df['first_crash_type'])
nullfree_crashes_df['trafficway_type']= label_encoder.fit_transform(nullfree_crashes_df['trafficway_type'])
nullfree_crashes_df['alignment']= label_encoder.fit_transform(nullfree_crashes_df['alignment'])
nullfree_crashes_df['roadway_surface_cond']= label_encoder.fit_transform(nullfree_crashes_df['roadway_surface_cond'])
nullfree_crashes_df['road_defect']= label_encoder.fit_transform(nullfree_crashes_df['road_defect'])
nullfree_crashes_df['crash_type']= label_encoder.fit_transform(nullfree_crashes_df['crash_type'])
nullfree_crashes_df['damage']= label_encoder.fit_transform(nullfree_crashes_df['damage'])
nullfree_crashes_df['prim_contributory_cause']= label_encoder.fit_transform(nullfree_crashes_df['prim_contributory_cause'])
nullfree_crashes_df['sec_contributory_cause']= label_encoder.fit_transform(nullfree_crashes_df['sec_contributory_cause'])
nullfree_crashes_df

,Unnamed: 0,posted_speed_limit,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,damage,prim_contributory_cause,sec_contributory_cause,injuries_total,crash_hour,crash_day_of_week,crash_month,severity
0,0,30,1,2,4,0,5,3,0,1,0,2,36,26,3.0,19,3,9,9.0
1,1,50,3,2,1,10,3,3,0,1,1,2,19,19,0.0,18,6,9,2.0
2,2,30,1,2,3,7,2,3,0,1,1,2,17,28,0.0,14,7,7,1.0
3,3,30,3,2,1,15,8,3,0,1,1,2,18,26,0.0,23,4,8,2.0
4,4,15,1,2,3,10,11,3,0,1,0,2,19,8,1.0,12,6,8,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769976,794951,30,3,2,3,7,10,3,0,1,1,1,21,36,0.0,7,2,11,1.0
769977,794952,30,3,11,5,15,11,3,5,5,1,1,36,26,0.0,18,3,10,2.0
769978,794953,30,3,2,3,7,10,3,0,1,1,2,21,21,0.0,23,7,11,1.0
769979,794954,30,3,2,1,17,8,3,0,1,0,2,36,26,0.0,18,2,11,4.0
769980,794955,30,3,2,1,0,8,3,5,5,1,2,18,26,0.0,19,2,11,2.0

In [6]:
nullfree_crashes_df.to_csv("labelencoded_df.csv")

In [7]:
nullfree_crashes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 769981 entries, 0 to 769980
Data columns (total 19 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Unnamed: 0               769981 non-null  int64
 1   posted_speed_limit       769981 non-null  int64
 2   device_condition         769981 non-null  int64
 3   weather_condition        769981 non-null  int64
 4   lighting_condition       769981 non-null  int64
 5   first_crash_type         769981 non-null  int64
 6   trafficway_type          769981 non-null  int64
 7   alignment                769981 non-null  int64
 8   roadway_surface_cond     769981 non-null  int64
 9   road_defect              769981 non-null  int64
 10  crash_type               769981 non-null  int64
 11  damage                   769981 non-null  int64
 12  prim_contributory_cause  769981 non-null  int64
 13  sec_contributory_cause   769981 non-null  int64
 14  injuries_total           769981 non-null  float64
 15  crash_hour               769981 non-null  int64
 16  crash_day_of_week        769981 non-null  int64
 17  crash_month              769981 non-null  int64
 18  severity                 769981 non-null  float64
dtypes: float64(2), int64(17)
memory usage: 111.6 MB

In [8]:
severity = nullfree_crashes_df['severity']
severity

0         9.0
1         2.0
2         1.0
3         2.0
4         3.0
         ...
769976    1.0
769977    2.0
769978    1.0
769979    4.0
769980    2.0
Name: severity, Length: 769981, dtype: float64

In [9]:
BaseCheck = (nullfree_crashes_df['severity']-1)//2
BaseCheck

0         4.0
1         0.0
2         0.0
3         0.0
4         1.0
         ...
769976    0.0
769977    0.0
769978    0.0
769979    1.0
769980    0.0
Name: severity, Length: 769981, dtype: float64

In [10]:
severity.unique()

array([ 9.,  2.,  1.,  3.,  5., 15.,  4., 10.,  7.,  6.,  8., 11., 12.,
       13., 20., 19., 27., 14., 16., 32., 17., 29., 36., 44., 23., 37.,
       43., 30., 22., 39., 50., 18., 21., 42., 46., 24., 26., 25., 28.,
       61., 38., 48., 49., 34., 31., 45., 40., 35., 33.])

In [11]:
data = nullfree_crashes_df.drop(columns='severity')
y = BaseCheck

In [12]:
X = MinMaxScaler().fit_transform(data)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state = 42)

In [14]:
def MAE(yTrue,yPred,len): #Calculates the MAE
  #le = np.count_nonzero(yTrue)
  sum = 0
  for i in range(len):
    sum += abs((yTrue[i] - yPred[i])/len)
  if(sum.shape==()):
    return (sum)
  return(sum[0])
def MSE(yTrue,yPred,len): #Calculates the MSE
  # len = np.count_nonzero(yTrue)
  sum = 0
  for i in range(len):
    sum += (abs((yTrue[i] - yPred[i])/len))**2
  if(sum.shape==()):
    return (sum*len)
  return(sum[0]*len)
def RMSE(yTrue,yPred,len): #Calculates the RMSE
  # len = np.count_nonzero(yTrue)
  sum = 0
  for i in range(len):
    sum += (abs((yTrue[i] - yPred[i])/len))**2
  if(sum.shape==()):
    return ((sum*len)**0.5)
  return((sum[0]*len)**0.5)
def AdjustedR2(yTrue,yPred,p,len): #Calculates the Adjusted R2
  R2=r2_score(yTrue,yPred)
  # len = np.count_nonzero(yTrue)
  val = (1-(1-R2*((len-1)/(len-p-1))))
  return val

In [15]:
def PrintAll_(X_test,y_test,X_train,y_train):
    ModelNorm = LogisticRegression(max_iter=300)
    ModelNorm.fit(X_train,y_train)
    y_true = y_test.to_numpy()
    y_pred = ModelNorm.predict(X_test)
    y_trueTrain = y_train.to_numpy()
    y_predTrain = ModelNorm.predict(X_train)
    parameters = X_train.shape[1]
    lenTrain = X_train.shape[0]
    lenTest = X_test.shape[0]
    # for i in range(100):
    #     print(y_trueTrain[i],y_predTrain[i])
    print("Training Data :")
    print(f"MAE for training data {MAE(y_trueTrain,y_predTrain,lenTrain)}")
    print(f"MSE for training data {MSE(y_trueTrain,y_predTrain,lenTrain)}")
    print(f"RMSE for training data {RMSE(y_trueTrain,y_predTrain,lenTrain)}")
    print(f"R2 Score for training data {r2_score(y_trueTrain,y_predTrain)}")
    print(f"Adjusted R2 Score for training data {AdjustedR2(y_trueTrain,y_predTrain,parameters,lenTrain)}")
    # acc = accuracy_score(y_test, y_pred)
    print(f"Accuracy_score for training data {accuracy_score(y_trueTrain,y_predTrain)}")
    print("Testing Data :")
    print(f"MAE for testing data {MAE(y_true,y_pred,lenTest)}")
    print(f"MSE for testing data {MSE(y_true,y_pred,lenTest)}")
    print(f"RMSE for testing data {RMSE(y_true,y_pred,lenTest)}")
    print(f"R2 Score for testing data {r2_score(y_true,y_pred)}")
    print(f"Adjusted R2 Score for testing data {AdjustedR2(y_true,y_pred,parameters,lenTest)}")
    print(f"Accuracy_score for testing data {accuracy_score(y_true,y_pred)}")

In [16]:
X_test

array([[0.72033637, 0.3030303 , 0.14285714, ..., 0.43478261, 0.16666667,
        0.90909091],
       [0.94642967, 0.3030303 , 0.42857143, ..., 0.69565217, 0.        ,
        0.72727273],
       [0.54831909, 0.25252525, 0.42857143, ..., 0.52173913, 0.83333333,
        0.45454545],
       ...,
       [0.11586819, 0.3030303 , 0.42857143, ..., 0.34782609, 0.16666667,
        0.54545455],
       [0.92118925, 0.3030303 , 0.42857143, ..., 0.69565217, 1.        ,
        0.54545455],
       [0.87218773, 0.3030303 , 0.14285714, ..., 0.47826087, 0.        ,
        0.63636364]])

In [17]:
PrintAll_(X_test,y_test,X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Training Data :
MAE for training data 0.30083248915540595
MSE for training data 0.4545507675515874
RMSE for training data 0.6742038026825327
R2 Score for training data 0.14178257457130683
Adjusted R2 Score for training data 0.14178671780402663
Accuracy_score for training data 0.7500211044442713
Testing Data :
MAE for testing data 0.2950252277642511
MSE for testing data 0.43793710267102076
RMSE for testing data 0.6617681638391354
R2 Score for testing data 0.14807728903722217
Adjusted R2 Score for testing data 0.1480945992451913
Accuracy_score for testing data 0.753748449645123

In [18]:
OHE=OneHotEncoder()

In [19]:
data = pd.read_csv('model_df.csv')

In [20]:
# data['traffic_control_device']= data['traffic_control_device'].astype('category')
data['device_condition']= data['device_condition'].astype('category')
data['weather_condition']= data['weather_condition'].astype('category')
data['lighting_condition']= data['lighting_condition'].astype('category')
data['first_crash_type']= data['first_crash_type'].astype('category')
data['trafficway_type']= data['trafficway_type'].astype('category')
data['alignment']= data['alignment'].astype('category')
data['roadway_surface_cond']= data['roadway_surface_cond'].astype('category')
data['road_defect']= data['road_defect'].astype('category')
# data['report_type']= data['report_type'].astype('category')
data['crash_type']= data['crash_type'].astype('category')
data['damage']= data['damage'].astype('category')
data['prim_contributory_cause']= data['prim_contributory_cause'].astype('category')
data['sec_contributory_cause']= data['sec_contributory_cause'].astype('category')
# data['street_direction']= data['street_direction'].astype('category')
# data['most_severe_injury']= data['most_severe_injury'].astype('category')
# data= data.drop(columns = ['street_no','street_name'])

In [21]:
# data['traffic_control_device']= data['traffic_control_device'].cat.codes
data['device_condition']= data['device_condition'].cat.codes
data['weather_condition']= data['weather_condition'].cat.codes
data['lighting_condition']= data['lighting_condition'].cat.codes
data['first_crash_type']= data['first_crash_type'].cat.codes
data['trafficway_type']= data['trafficway_type'].cat.codes
data['alignment']= data['alignment'].cat.codes
data['roadway_surface_cond']= data['roadway_surface_cond'].cat.codes
data['road_defect']= data['road_defect'].cat.codes
# data['report_type']= data['report_type'].cat.codes
data['crash_type']= data['crash_type'].cat.codes
data['damage']= data['damage'].cat.codes
data['prim_contributory_cause']= data['prim_contributory_cause'].cat.codes
data['sec_contributory_cause']= data['sec_contributory_cause'].cat.codes
# data['street_direction']= data['street_direction'].cat.codes
# data['most_severe_injury']= data['most_severe_injury'].cat.codes
# data.dropna (axis=1)

In [22]:
data

,Unnamed: 0,posted_speed_limit,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,damage,prim_contributory_cause,sec_contributory_cause,injuries_total,crash_hour,crash_day_of_week,crash_month,severity
0,0,30,1,2,4,0,5,3,0,1,0,2,36,26,3.0,19,3,9,9.0
1,1,50,3,2,1,10,3,3,0,1,1,2,19,19,0.0,18,6,9,2.0
2,2,30,1,2,3,7,2,3,0,1,1,2,17,28,0.0,14,7,7,1.0
3,3,30,3,2,1,15,8,3,0,1,1,2,18,26,0.0,23,4,8,2.0
4,4,15,1,2,3,10,11,3,0,1,0,2,19,8,1.0,12,6,8,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769976,794951,30,3,2,3,7,10,3,0,1,1,1,21,36,0.0,7,2,11,1.0
769977,794952,30,3,11,5,15,11,3,5,5,1,1,36,26,0.0,18,3,10,2.0
769978,794953,30,3,2,3,7,10,3,0,1,1,2,21,21,0.0,23,7,11,1.0
769979,794954,30,3,2,1,17,8,3,0,1,0,2,36,26,0.0,18,2,11,4.0
769980,794955,30,3,2,1,0,8,3,5,5,1,2,18,26,0.0,19,2,11,2.0

In [23]:
print(data.isna().values.any())

False

In [24]:
enc_data = pd.DataFrame(OHE.fit_transform(
    data[['device_condition','weather_condition','lighting_condition','first_crash_type','trafficway_type','alignment','roadway_surface_cond','road_defect','crash_type','damage','prim_contributory_cause','sec_contributory_cause']]).toarray())
enc_data

,0,1,2,3,4,5,6,7,8,9,...,159,160,161,162,163,164,165,166,167,168
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769976,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
769977,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769978,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769979,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769980,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
print(enc_data.isna().values.any())

False

In [26]:
New_df = data.join(enc_data)
New_df

,Unnamed: 0,posted_speed_limit,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,...,159,160,161,162,163,164,165,166,167,168
0,0,30,1,2,4,0,5,3,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,50,3,2,1,10,3,3,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,30,1,2,3,7,2,3,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,30,3,2,1,15,8,3,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,15,1,2,3,10,11,3,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769976,794951,30,3,2,3,7,10,3,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
769977,794952,30,3,11,5,15,11,3,5,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769978,794953,30,3,2,3,7,10,3,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769979,794954,30,3,2,1,17,8,3,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769980,794955,30,3,2,1,0,8,3,5,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
New_df = New_df.drop(columns=['device_condition','weather_condition','lighting_condition','first_crash_type','trafficway_type','alignment','roadway_surface_cond','road_defect','crash_type','damage','prim_contributory_cause','sec_contributory_cause'])

In [28]:
New_df.dropna()

,Unnamed: 0,posted_speed_limit,injuries_total,crash_hour,crash_day_of_week,crash_month,severity,0,1,2,...,159,160,161,162,163,164,165,166,167,168
0,0,30,3.0,19,3,9,9.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,50,0.0,18,6,9,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,30,0.0,14,7,7,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,30,0.0,23,4,8,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,15,1.0,12,6,8,3.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769976,794951,30,0.0,7,2,11,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
769977,794952,30,0.0,18,3,10,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769978,794953,30,0.0,23,7,11,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769979,794954,30,0.0,18,2,11,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769980,794955,30,0.0,19,2,11,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
yValOhe = New_df['severity']
yValOhe

0         9.0
1         2.0
2         1.0
3         2.0
4         3.0
         ...
769976    1.0
769977    2.0
769978    1.0
769979    4.0
769980    2.0
Name: severity, Length: 769981, dtype: float64

In [30]:
New_df = New_df.drop(columns=['severity'])

In [31]:
XValOhe = New_df
XValOhe.columns = XValOhe.columns.astype(str)

In [32]:
X_normOhe = StandardScaler().fit_transform(XValOhe)

In [33]:
BaseCheckOHE = (yValOhe-1)//2
BaseCheckOHE

0         4.0
1         0.0
2         0.0
3         0.0
4         1.0
         ...
769976    0.0
769977    0.0
769978    0.0
769979    1.0
769980    0.0
Name: severity, Length: 769981, dtype: float64

In [34]:
X_trainOhe, X_testOhe, y_trainOhe, y_testOhe = train_test_split(X_normOhe,BaseCheckOHE, test_size=0.2, random_state=42)

In [35]:
PrintAll_(X_testOhe, y_testOhe,X_trainOhe, y_trainOhe)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Training Data :
MAE for training data 0.2938631522894534
MSE for training data 0.440142925789565
RMSE for training data 0.6634326836910923
R2 Score for training data 0.16898539050681893
Adjusted R2 Score for training data 0.16903341268798366
Accuracy_score for training data 0.7552176679913764
Testing Data :
MAE for testing data 0.28922641350161893
MSE for testing data 0.4261381715229957
RMSE for testing data 0.6527925945681337
R2 Score for testing data 0.17102984854582026
Adjusted R2 Score for testing data 0.17122442681208772
Accuracy_score for testing data 0.7582290564101898